### ISSUE TITLE
font-awesome ne charge pas les fonts

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io-original#92]
Les fonts ne semblent pas inclu dans le projet, mais aussi bien gérer les librairies externes avec `yarn`.

## Pourquoi pas bower?

Bower indique de ne plus utiliser bower

> npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Mais visiblement, c'est pas aussi simple que ce que ça indique. On prendra `yarn` pour gérer ça quand ils auront un fix pour ces 2 issues:
https://github.com/sheerun/bower-away/issues/9
https://github.com/sheerun/bower-away/issues/11

__tldr__ je vais utiliser bower en attendant.

**Comment by GabLeRoux** [comment]
Si on veut installer des dépendances par `bower`, `yarn`, ou `npm`, on va devoir setuper une job travis qui va builder le site et déployer dans `gh-pages`.

Sur mon site perso, j'ai le même problème et je fais mes déploiements manuellement (quelques commandes dans mon readme). J'ai expérimenté avec `travis` et `pages` dernièrement et c'est possible de déployer automatiquement vers `gh-pages` assez simplement, voici un exemple (untested):

```yaml
language: ruby
rvm:
- 2.4.2

cache:
  directories:
    - assets/bower_components

before_script:
  - npm install -g grunt bower
  - bower install

script:
  - bundle exec jekyll build

deploy:
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
```

On doit simplement ajouter une env var `GITHUB_TOKEN` afin que `travis` ait les droits de push dans le repo.

```bash
gem install travis
travis encrypt GITHUB_TOKEN=<the_token> --add env.matrix
git add .travis.yml
# etc...
```
